### ISSUE TITLE
Some questions.

### ISSUE THREAD

**Issue by nikitabalakin** [locuslab/wanda#12]
Hi, please answer a few questions.

Can I prune a model combined with LORA?

Can I prune the model and then use LORA?

Is it possible to prune Falcon 7b and 40b models?

Can you place ready-made models?

Is it possible to compress models after prune?

**Comment by Eric-mingjie** [comment]
Our method is a general pruning method, as demonstrated in our paper. It is not limited to LLMs but is also effective for image classification models. As for your last question, do you mean "how to quantize a pruned model"?

**Comment by nikitabalakin** [comment]
oh, yes, it's possible?

**Comment by Eric-mingjie** [comment]
Yes, hypothetically it is possible. But i think the more common approach is to do joint quantization and pruning, as has been explored in previous work.
