### ISSUE TITLE
How to use sparseGPT to prune the output dimension?

### ISSUE THREAD

**Issue by wfan1203** [locuslab/wanda#15]
How to use sparseGPT to prune the output dimension? When I was calculating the Hessian matrix, the input dimension did not match the Hessian matrix dimension

**Comment by Eric-mingjie** [comment]
Could you specify what do you mean by pruning the output dimension?

**Comment by wfan1203** [comment]
感谢您的来信，我将及时回复您！                                                   ——武凡

**Comment by wfan1203** [comment]
感谢您的来信，我将及时回复您！                                                   ——武凡
