### ISSUE TITLE
can not reproduce the results of figure 3

### ISSUE THREAD

**Issue by HaihangWu** [locuslab/wanda#19]
Dear author:
      When I try to repeat the results of figure 3 for the effect of calibration set size, I get 12.57 for Llama-7B if I set the sample size =1. I only change the following command to set the default value 1, and nothing else is changed. Could you help check this?
 parser.add_argument('--nsamples', type=int, default=1, help='Number of calibration samples.')

**Comment by Eric-mingjie** [comment]
Hi, I just rerun the default pruning command with `--nsamples` to be 1 and got a ppl of 7.64. Could you give me the exact command you are using?

**Comment by HaihangWu** [comment]
Thanks. I can reproduce your results now.
