### ISSUE TITLE
how to save the model file/ckpt?

### ISSUE THREAD

**Issue by JianbangZ** [locuslab/wanda#2]
right now it only saves the log result

**Comment by Eric-mingjie** [comment]
see this [pull request](https://github.com/locuslab/wanda/pull/3) for a fix, we will be adding support for saving model shortly.

**Comment by Eric-mingjie** [comment]
Added support in this recent [commit](https://github.com/locuslab/wanda/blob/main/main.py#L39), now you can set the path to save pruned model via `--save_model` argument.
