### ISSUE TITLE
Structured 2:4 sparsity pattern supporting GPU

### ISSUE THREAD

**Issue by kiucho** [locuslab/wanda#20]
Hello. Thanks for sharing your great works.

I want to see how much faster my model is to when pruned with a structured 2:4 sparsity pattern rather than regular pruning on GPU A6000.
In the paper, looking at table 2, I can compare the wikitext validation perplexity performance with the normal 50% sparsitifed model by applying 2:4 and 4:8 sparsity patterns. 
As far as I know, to use the 2:4 sparsity pattern, I need to use a GPU with a sparse tensor core(such as the A100 GPU).
I was wondering which GPU did you use for this performance evaluation and is it possible to do it with the A6000 GPU?
If I'm misunderstanding something, I'd appreciate it if you could point it out.

Thank you.

**Comment by Eric-mingjie** [comment]
Hi, Thanks for your interest in our work. 

The experiments for this paper were run on A6000 GPU. For structured 2:4 sparsity, it should work with any Ampere series GPUs [https://arxiv.org/abs/2104.08378](https://arxiv.org/abs/2104.08378). There may be some extra implementation needed for practical speedups but we didn't look into this at the time of writing this paper.
