### ISSUE TITLE
Some questions about the codes.

### ISSUE THREAD

**Issue by kiseliu** [locuslab/wanda#21]
Thanks for your simple but efficient work for pruning. 
I am reading your code, but I have some questions.

* Q1: I think that the class `WrappedGPT` in [lib/layerwrapper.py](https://github.com/locuslab/wanda/blob/main/lib/layerwrapper.py) has a function of `LayerNorm`?    
* Q2: I don't understand the following implementation in [lib/prune.py](https://github.com/locuslab/wanda/blob/main/lib/prune.py), could you give some explanations?
  ```
  150        def add_batch(name):
  151            def tmp(_, inp, out):
  152                wrapped_layers[name].add_batch(inp[0].data, out.data)
  153            return tmp
  154
  155        handles = []
  156        for name in wrapped_layers:
  157            handles.append(subset[name].register_forward_hook(add_batch(name)))
  158        for j in range(args.nsamples):
  159            with torch.no_grad():
  160                outs[j] = layer(inps[j].unsqueeze(0), attention_mask=attention_mask, position_ids=position_ids)[0]
  161        for h in handles:
  162            h.remove()
  
  ...
  
  204        for j in range(args.nsamples):
  205            with torch.no_grad():
  206                outs[j] = layer(inps[j].unsqueeze(0), attention_mask=attention_mask, position_ids=position_ids)[0]
  207        inps, outs = outs, inps
  ```
  **These computations are equal to the original forward pass computations in transformers?**

**Comment by Eric-mingjie** [comment]
For the first question, can you point me which line has `LayerNorm`? 

For the second question, this is to collect the input activations as the batch is being forwarded in the current layer. The layerwrapper will collect these statistics and we can later retrieve them from [https://github.com/locuslab/wanda/blob/main/lib/layerwrapper.py#L35](https://github.com/locuslab/wanda/blob/main/lib/layerwrapper.py#L35).

**Comment by kiseliu** [comment]
> For the first question, can you point me which line has `LayerNorm`?
> 
> For the second question, this is to collect the input activations as the batch is being forwarded in the current layer. The layerwrapper will collect these statistics and we can later retrieve them from https://github.com/locuslab/wanda/blob/main/lib/layerwrapper.py#L35.

I mean the `norm`operation in https://github.com/locuslab/wanda/blob/main/lib/layerwrapper.py#L35 plays a role of `LayerNorm`? 

Now I have understood that `add_batch()` in the `layerwrapper.py` will give us the mean input activations of a batch and the code of line 150-162 in [lib/prune.py](https://github.com/locuslab/wanda/blob/main/lib/prune.py). Thanks for your reply.
