### ISSUE TITLE
calibration data seq_length

### ISSUE THREAD

**Issue by kiucho** [locuslab/wanda#22]
Hi, I have a question about calibration data (128, 2048 tokens, respectively)

Is there a particular reason to use 2048 tokens for each data?
I tracked [SparseGPT](https://arxiv.org/pdf/2301.00774.pdf), [GPTQ](https://arxiv.org/pdf/2210.17323.pdf), but I couldn't find it.
I hope I can get some insight.

Thank you.

**Comment by Eric-mingjie** [comment]
2048 is the maximum context size of the OPT and LLaMA models. In other words, these LLMs can process a sequence with up to 2048 tokens.
