### ISSUE TITLE
Fine-tune the pruned model

### ISSUE THREAD

**Issue by guozhiyu** [locuslab/wanda#24]
I noticed that in the recent version, the Full Parameter Fine-tuning was added. How to fine-tune the Wanda pruned model?

**Comment by Eric-mingjie** [comment]
While fine-tuning is not part of our proposed method Wanda itself, in our updated paper, we conduct fine-tuning analysis to study how it can mitigate the performance drop during pruning. 

To this end, we have experimented with both LoRA fine-tuning and full parameter fine-tuning. For LoRA, we apply LoRA adapter on `q_proj` and `v_proj`. The full parameter fine-tuning is to follow the conventional setting of fine-tuning in existing pruning literatures, where we keep the pruning mask fixed while updating the kept weights. At present, we are planning to release the code for fine-tuning.
