### ISSUE TITLE
Where is cache['attention_mask']?

### ISSUE THREAD

**Issue by JohnneyQin** [locuslab/wanda#48]
When using the sparsegpt pruning method, the following code is used, but kwargs['attention_mask'] appears to be None, resulting in a subsequent error.
class Catcher(nn.Module):
        def __init__(self, module):
                super().__init__()
                self.module = module
        def forward(self, inp, **kwargs):
                inps[cache['i']] = inp
                cache['i'] += 1
                cache['attention_mask'] = kwargs['attention_mask']
                cache['position_ids'] = kwargs['position_ids']
                raise ValueError

**Comment by Eric-mingjie** [comment]
This is the argument that the LLaMA2 model expect https://github.com/huggingface/transformers/blob/v4.39.0/src/transformers/models/llama/modeling_llama.py#L704
