### ISSUE TITLE
question about the code in the sparse_trainer.py

### ISSUE THREAD

**Issue by hhhhain** [locuslab/wanda#49]
I'm running the code for sparse_trainer.py, it raises an error:

AttributeError: 'SparseTrainer' object has no attribute 'do_grad_scaling'.

I checked the code, and the 'do_grad_scaling' is only defined in the trainer.py in the dense_ft folder, but weird, you import trainer from transformers.trainer, which does not contain 'do_grad_scaling'.

I wonder which trainer class should be the right one? Could you open-source the dense finetune code for the sparse_trainer.py?

**Comment by Eric-mingjie** [comment]
The `sparse_trainer` class should be the right one to use. It is simply applying the pruning mask over the gradient so that the pruned weights are not updated, as is the common setup for fine-tuning a pruned model (https://arxiv.org/abs/1506.02626 and https://arxiv.org/abs/1803.03635)

**Comment by hhhhain** [comment]
solved by changing the version transformer.
