### ISSUE TITLE
"line 39, in main     parser.add_argument('--save_model', **typr**=str, default=None, help='Path to save the pruned model.')"

### ISSUE THREAD

**Issue by Alignment-Lab-AI** [locuslab/wanda#5]
little typo there, would putting my own dataset into here made a difference? ive been having an itch since i heard about sparsegpt to see how close i can tool it to task orient a model

**Comment by Eric-mingjie** [comment]
Hi, Thanks for your interest to our work! To support custom dataset to use as calibration set, you can add a custom loader in this [function](https://github.com/locuslab/wanda/blob/main/lib/data.py#L69).

**Comment by Alignment-Lab-AI** [comment]
i will be sure to return results when i determine! currently im modifying it to run a parallel session in which seperate pruning methods are attempted and perplexity computed, then as  good values are found, execute on the main model

however running with the repository, even after fixing the typo, im still having a hard time actually saving the model, the most i can get it to do is save the models unmodified weights if at all
it appears to be conflating the save arg with the save_model arg in places in the code

**Comment by Eric-mingjie** [comment]
The argument [`--save_model`](https://github.com/locuslab/wanda/blob/main/main.py#L88) was added to allow the custom demand of saving pruned models. From this [line](https://github.com/locuslab/wanda/blob/main/main.py#L75), you can see if the model is pruned when the sparsity is a non-zero value.
