### ISSUE TITLE
why choosing vicuna as the tokenizer

### ISSUE THREAD

**Issue by hhhhain** [locuslab/wanda#53]
The tokenizer is defined as follows in the finetune_lm.py in the lora_ft folder: 

    # tokenizer = AutoTokenizer.from_pretrained(model_args.config_name, use_fast=False)
    ## we use the tokenizer from vicuna
    if "decapoda-research" in model_args.config_name:
        tokenizer = AutoTokenizer.from_pretrained(
            "lmsys/vicuna-13b-delta-v0",
            cache_dir=model_args.cache_dir,
            padding_side="right",
            use_fast=True,
        )

Could you please explain why choosing the tokenizer from Vicuna?

**Comment by Eric-mingjie** [comment]
There were some issues with LLaMA tokenizer with respect to special tokens, where Vicuna got it right. But with LLaMA2 and LLaMA3, there should be no problem.

**Comment by hhhhain** [comment]
Many thanks.
