### ISSUE TITLE
Ambiguous result for LLAMA-2-13b

### ISSUE THREAD

**Issue by Qian2333** [locuslab/wanda#54]
using the original code, prune_wanda with sparasity 50%, the ppl is 50000+
while for the original llama-2-13b, the ppl is regular 4.5+.
Before that, the code perform well for llama-7b and llama-2-7b, all the ppl result is right refer to the paper.
Is there any more arguments should be set for the code for 13b model?

为了避免我拙劣的英语影响表达，同时看了作者大大的履历，我用中文再写一遍：
我用了仓库里的代码，在7b上的llama、llama2模型都表现正常，但是在13b的llama2模型上表现异常。
我再三确定了：
ppl评价和13b模型都没有问题，不剪枝的llama2的ppl表现正常。
prune代码就是copy的作者的，我自己检查也没有任何问题。
我用的所有参数基本上都是作者代码中默认的参数。
请问作者是否在13b上测试过代码可用性呢？是需要一些特殊的参数修改吗？

**Comment by Qian2333** [comment]
upd: the same code perform well on llama-13b.

**Comment by Eric-mingjie** [comment]
You don't need any changes for LLaMA2-13B model. I have tested this multiple times before. Did you direct run the commands suggested in the README?

**Comment by Qian2333** [comment]
Thank you for your patient response. I have found that the issue seems to be with the version of llama-2-13b-hf that I was using. After downloading a new version, I obtained reasonable results.
